# Generated by Django 5.2.5 on 2025-08-27 15:30

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('reviewing', 'Reviewing'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='applied', max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='emb',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='experience',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cv',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='cv',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jd',
            name='emb',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name='jd',
            name='employment_type',
            field=models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract'), ('intern', 'Intern')], default='full-time', max_length=20),
        ),
        migrations.AddField(
            model_name='jd',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='jd',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='jd',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='jd',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='cv',
            name='resume_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='cv',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='cv_search_gin'),
        ),
        migrations.AddIndex(
            model_name='cv',
            index=models.Index(fields=['-updated_at'], name='cv_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='cv',
            index=pgvector.django.indexes.HnswIndex(fields=['emb'], name='cv_emb_hnsw'),
        ),
        migrations.AddIndex(
            model_name='jd',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='jd_search_gin'),
        ),
        migrations.AddIndex(
            model_name='jd',
            index=models.Index(fields=['-created_at'], name='jd_posted_idx'),
        ),
        migrations.AddIndex(
            model_name='jd',
            index=pgvector.django.indexes.HnswIndex(fields=['emb'], name='jd_emb_hnsw'),
        ),
        migrations.AddField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='matching.cv'),
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='matching.jd'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'candidate'], name='app_job_cand_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['-created_at'], name='app_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'candidate')},
        ),
    ]
