# Generated by Django 5.2.5 on 2025-08-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jd',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
